name: Continuous Delivery

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: [ main ]
    tags:
      - '*'

jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Extract Tag name
        run: |
          echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Set Environment Variable ENV
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "REF=dev" >> $GITHUB_ENV
            echo "VERSION=latest" >> $GITHUB_ENV
          fi

      - name: Print VERSION as $GITHUB_REF_NAME
        run: |
          echo "Name from VERSION 2 step: $VERSION"   

      - name: Run Python script
        run: |
          python3 TriggerWorkers.py ${{ secrets.WORKER_ANDROID_SECRET }} $VERSION $REF
