name: Continuous Delivery

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: [ main ]
    tags:
      - '*'

jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set Environment Variable ENV
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "REF=dev" >> $GITHUB_ENV
          elif [ "${GITHUB_REF##*/}" != "main" ]; then
            echo "REF=main" >> $GITHUB_ENV
            echo "CORE_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
          fi

        #REF - dev or prod pushing worker to ecr
        #VERSION with this version will build worker
        #CORE_TAG pushing core  to ecr = tag 'latest'
      - name: Print VERSION as $GITHUB_REF_NAME
        run: |
          echo "REF: $REF"   
          echo "VERSION: $VERSION"   
          echo "CORE_TAG: $CORE_TAG"

      - name: Run Python script
        run: |
          python3 TriggerWorkers.py ${{ secrets.WORKER_ANDROID_SECRET }} $VERSION $REF
